<a href="https://colab.research.google.com/github/maunzeb/MachineLearning/blob/main/FeedingData0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense

In [2]:
# loading and inspecting data
from google.colab import files
uploaded = files.upload()

import io
df2 = pd.read_csv(io.BytesIO(uploaded['Meal_Patterns_Mawere_1_2.csv']))
# Dataset is now stored in a Pandas Dataframe

print(df2.shape)
df2.describe()

Saving Meal_Patterns_Mawere_1_2.csv to Meal_Patterns_Mawere_1_2.csv
(120, 13)

,Amt1,Amt2,Duration1,Duration2,TotalAmt,LatencyMeal1,LatencyMeal2,TotalTimeEating,PercentTimeEating,EatingRateMgMin,DailyFoodIntake,BrainRegion,DrugTreatment
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,2.284667,2.358917,31.456667,22.930833,8.327833,52.183333,72.632917,88.447500,24.778583,22.909750,19.999750,0.508333,1.450000
std,1.665822,1.503824,29.917199,17.938155,3.202650,50.132594,56.566615,48.740018,13.342637,9.078662,5.893282,0.502027,1.114081
min,0.210000,0.210000,0.220000,2.600000,0.390000,1.000000,15.400000,13.600000,3.790000,1.100000,3.090000,0.000000,0.000000
25%,0.887500,1.090000,13.500000,10.850000,6.555000,16.000000,31.750000,53.300000,14.970000,17.950000,16.692500,0.000000,0.000000
50%,2.220000,2.275000,23.950000,18.400000,8.475000,34.000000,58.050000,80.450000,22.345000,23.250000,21.030000,1.000000,1.000000
75%,3.162500,3.335000,38.850000,28.600000,10.517500,71.250000,98.075000,113.275000,31.455000,29.225000,23.247500,1.000000,2.000000
max,9.050000,7.730000,202.900000,90.450000,16.500000,309.000000,304.700000,285.600000,79.330000,45.800000,38.510000,1.000000,3.000000

Looks like we have missing values since the variables counts have different totals. I'll hae to deal with those missing values.

The first line of code creates an object of the target variable, while the second line of code gives us the list of all the features, excluding the target variable 'LatencyMeal1'.

The third line normalizes the predictors. This is important because the units of the variables differ significantly and may influence the modeling process. To prevent this, we will do normalization via scaling of the predictors between 0 and 1.

The fourth line displays the summary of the normalized data. We can see that all the independent variables have now been scaled between 0 and 1. The target variable remains unchanged.

In [3]:
# Dealing with missing values
df2['Amt1'].fillna(df2['Amt1'].mean(), inplace=True) 
df2['Amt2'].fillna(df2['Amt2'].mean(), inplace=True)
df2['Duration1'].fillna(df2['Duration1'].mean(), inplace=True)
df2['Duration2'].fillna(df2['Duration2'].mean(), inplace=True)
df2['TotalAmt'].fillna(df2['TotalAmt'].mean(), inplace=True)
df2['LatencyMeal1'].fillna(df2['LatencyMeal1'].mean(), inplace=True)
df2['LatencyMeal2'].fillna(df2['LatencyMeal2'].mean(), inplace=True)
df2['TotalTimeEating'].fillna(df2['TotalTimeEating'].mean(), inplace=True)
df2['PercentTimeEating'].fillna(df2['PercentTimeEating'].mean(), inplace=True)
df2['EatingRateMgMin'].fillna(df2['EatingRateMgMin'].mean(), inplace=True)
df2['DailyFoodIntake'].fillna(df2['DailyFoodIntake'].mean(), inplace=True)
#df2['Is_graduate'].fillna(1,inplace=True)
df2.describe()

,Amt1,Amt2,Duration1,Duration2,TotalAmt,LatencyMeal1,LatencyMeal2,TotalTimeEating,PercentTimeEating,EatingRateMgMin,DailyFoodIntake,BrainRegion,DrugTreatment
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,2.284667,2.358917,31.456667,22.930833,8.327833,52.183333,72.632917,88.447500,24.778583,22.909750,19.999750,0.508333,1.450000
std,1.665822,1.503824,29.917199,17.938155,3.202650,50.132594,56.566615,48.740018,13.342637,9.078662,5.893282,0.502027,1.114081
min,0.210000,0.210000,0.220000,2.600000,0.390000,1.000000,15.400000,13.600000,3.790000,1.100000,3.090000,0.000000,0.000000
25%,0.887500,1.090000,13.500000,10.850000,6.555000,16.000000,31.750000,53.300000,14.970000,17.950000,16.692500,0.000000,0.000000
50%,2.220000,2.275000,23.950000,18.400000,8.475000,34.000000,58.050000,80.450000,22.345000,23.250000,21.030000,1.000000,1.000000
75%,3.162500,3.335000,38.850000,28.600000,10.517500,71.250000,98.075000,113.275000,31.455000,29.225000,23.247500,1.000000,2.000000
max,9.050000,7.730000,202.900000,90.450000,16.500000,309.000000,304.700000,285.600000,79.330000,45.800000,38.510000,1.000000,3.000000

In [4]:
from sklearn.metrics.pairwise import normalize
#creating arrays for the features and the response variable
# the response variable/targetvariable for now is the Latency_Meal_1
from sklearn.preprocessing import StandardScaler
df2[['Amt1','Amt2','Duration1','Duration2','TotalAmt','LatencyMeal1','LatencyMeal2',
     'TotalTimeEating','PercentTimeEating','EatingRateMgMin','DailyFoodIntake']] = StandardScaler().fit_transform(df2[['Amt1','Amt2','Duration1','Duration2','TotalAmt','LatencyMeal1','LatencyMeal2','TotalTimeEating','PercentTimeEating','EatingRateMgMin','DailyFoodIntake']])
print(df2['Amt1'].var());print(df2['Amt2'].var());print(df2['Duration1'].var());print(df2['Duration2'].var());print(df2['TotalAmt'].var());print(df2['LatencyMeal1'].var());print(df2['LatencyMeal2'].var());print(df2['TotalTimeEating'].var());print(df2['PercentTimeEating'].var());print(df2['EatingRateMgMin'].var());print(df2['DailyFoodIntake'].var())

1.0084033613445378
1.0084033613445376
1.0084033613445378
1.0084033613445378
1.0084033613445378
1.0084033613445378
1.0084033613445378
1.0084033613445378
1.0084033613445378
1.0084033613445378
1.0084033613445378

In [6]:
print(df2.info)
df2.describe
df2 = df2.dropna(how='any',axis=0)

<bound method DataFrame.info of          Amt1      Amt2  Duration1  Duration2  TotalAmt  LatencyMeal1  \
0   -0.551380 -0.232992  -0.270428  -0.746271 -0.115334     -0.824933
1   -0.798537  0.795357  -0.257002   0.496503 -0.416343     -0.604594
2   -0.454929  0.281182   0.196136  -0.292826 -0.250161     -0.945117
3    0.172005  0.227762  -0.055607   0.440523  0.533715      0.757496
4   -0.045011 -0.560195  -0.763844  -1.014979 -0.569983      0.757496
..        ...       ...        ...        ...       ...           ...
115  1.154603 -0.373222   0.702978  -0.259238  0.066525     -0.584564
116  1.208857 -0.847331   1.474990  -1.068161  0.997770     -0.844963
117 -0.231885  0.134275  -0.471822   3.670617 -0.388123     -0.003672
118 -0.406703 -0.673714   0.562002  -0.203257  0.188810     -0.724779
119  1.522324 -1.374861   1.981833  -0.634310  0.866079     -0.824933

     LatencyMeal2  TotalTimeEating  PercentTimeEating  EatingRateMgMin  \
0        0.659805        -0.711784          -0.737460        -0.089567
1        0.059774        -0.225552          -0.245247        -0.388214
2       -0.311251        -0.270879          -0.291157        -0.222299
3       -0.149704         0.441987           0.432110         0.551973
4        0.666906        -1.171232          -1.203332        -0.532008
..            ...              ...                ...              ...
115      0.311858         0.075253           0.059564         0.087410
116     -0.611267         1.062139           1.062805         1.005475
117      0.656254        -1.486458          -0.382224        -0.355031
118     -0.985842         1.327918           1.330738         0.209081
119     -0.121301         1.472139           1.479004         0.872742

     DailyFoodIntake  BrainRegion  DrugTreatment
0           0.034122            0            0.0
1          -2.165693            0            0.0
2           0.419217            0            0.0
3           0.543606            0            0.0
4          -2.293490            0            0.0
..               ...          ...            ...
115        -0.275999            1            3.0
116         1.162145            1            3.0
117        -0.218065            1            3.0
118        -0.098787            1            3.0
119         0.495896            1            3.0

[120 rows x 13 columns]>

Creating the Training and Test Datasets
The first couple of lines creates arrays of independent (X) and dependent (y) variables, respectively. The third line splits the data into training and test dataset, while the fourth line prints the shape of the training set (93 observations of 13 variables) and test set (41 observations of 13 variables).

In [7]:
target_column = ['LatencyMeal1'] 
predictors = list(set(list(df2.columns))-set(target_column))

X = df2[predictors].values
y = df2[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(84, 12)
(36, 12)

Building the Deep Learning Regression Model
We will build a regression model using deep learning in Keras. To begin with, we will define the model. The first line of code below calls for the Sequential constructor. Note that we would be using the Sequential model because our network consists of a linear stack of layers. The second line of code represents the first layer which specifies the activation function and the number of input dimensions, which in our case is 13 predictors. Then we repeat the same process in the third and fourth line of codes for the hidden layers, this time without the input_dim parameter. The last line of code creates the output layer with one node that is supposed to output the number of unemployed in thousands.

The activation function used in the hidden layers is a rectified linear unit, or ReLU. It is the most widely used activation function because of its advantages of being nonlinear, as well as the ability to not activate all the neurons at the same time. In simple terms, this means that at a time, only a few neurons are activated, making the network sparse and very efficient

In [10]:
# Define model
model = Sequential()
model.add(Dense(500, input_dim=12, activation= "relu"))
model.add(Dense(100, activation= "relu"))
model.add(Dense(50, activation= "relu"))
model.add(Dense(1))
#model.summary() #Print model Summary

The next step is to define an optimizer and the loss measure for training. The mean squared error is our loss measure and the "adam" optimizer is our minimization algorithm. The main advantage of the "adam" optimizer is that we don't need to specify the learning rate as is the case with gradient descent; thereby saving us the task of optimizing the learning rate for our model. We achieve this task with the first line of the code below.

The second line of code fits the model on the training dataset. We also provide the argument, epochs, which represents the number of training iterations. We have taken 20 epochs.

In [11]:
import tensorflow as tf
df2.isnull().any()
np.array(df2, dtype=np.float_)
dftensor=tf.convert_to_tensor(df2)
model.compile(loss= "mean_squared_error" , optimizer="adam", metrics=["mean_squared_error"])
X_train = np.array([np.array(val) for val in X_train])
X_test = np.array([np.array(val) for val in X_test])
model.fit(X_train, y_train, epochs=20)

Epoch 1/20
3/3 [==============================] - 1s 9ms/step - loss: 0.6535 - mean_squared_error: 0.6535
Epoch 2/20
3/3 [==============================] - 0s 6ms/step - loss: 0.5168 - mean_squared_error: 0.5168
Epoch 3/20
3/3 [==============================] - 0s 5ms/step - loss: 0.4525 - mean_squared_error: 0.4525
Epoch 4/20
3/3 [==============================] - 0s 6ms/step - loss: 0.4037 - mean_squared_error: 0.4037
Epoch 5/20
3/3 [==============================] - 0s 8ms/step - loss: 0.3510 - mean_squared_error: 0.3510
Epoch 6/20
3/3 [==============================] - 0s 6ms/step - loss: 0.3115 - mean_squared_error: 0.3115
Epoch 7/20
3/3 [==============================] - 0s 5ms/step - loss: 0.2710 - mean_squared_error: 0.2710
Epoch 8/20
3/3 [==============================] - 0s 5ms/step - loss: 0.2404 - mean_squared_error: 0.2404
Epoch 9/20
3/3 [==============================] - 0s 5ms/step - loss: 0.2146 - mean_squared_error: 0.2146
Epoch 10/20
3/3 [==============================] - 0s 6ms/step - loss: 0.2002 - mean_squared_error: 0.2002
Epoch 11/20
3/3 [==============================] - 0s 5ms/step - loss: 0.1764 - mean_squared_error: 0.1764
Epoch 12/20
3/3 [==============================] - 0s 5ms/step - loss: 0.1636 - mean_squared_error: 0.1636
Epoch 13/20
3/3 [==============================] - 0s 6ms/step - loss: 0.1518 - mean_squared_error: 0.1518
Epoch 14/20
3/3 [==============================] - 0s 5ms/step - loss: 0.1381 - mean_squared_error: 0.1381
Epoch 15/20
3/3 [==============================] - 0s 5ms/step - loss: 0.1303 - mean_squared_error: 0.1303
Epoch 16/20
3/3 [==============================] - 0s 6ms/step - loss: 0.1094 - mean_squared_error: 0.1094
Epoch 17/20
3/3 [==============================] - 0s 5ms/step - loss: 0.1018 - mean_squared_error: 0.1018
Epoch 18/20
3/3 [==============================] - 0s 8ms/step - loss: 0.0909 - mean_squared_error: 0.0909
Epoch 19/20
3/3 [==============================] - 0s 5ms/step - loss: 0.0832 - mean_squared_error: 0.0832
Epoch 20/20
3/3 [==============================] - 0s 5ms/step - loss: 0.0744 - mean_squared_error: 0.0744